version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: admin321
      MYSQL_DATABASE: task_db
    ports:
      - 3306:3306

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
    ports:
      - 5000:5000
